config/routes.rb
ComicBook::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'profile',      :to => 'users#show',    :as => 'profile'
  get 'profile/edit', :to => 'users#edit',    :as => 'edit_profile'
  put 'profile',      :to => 'users#update',  :as => 'update_profile'

  get '/comic/:year/:month/:day', :to => 'comics#show_by_day', :as => 'archived'
  get '/blog/:year/:month/:day', :to => 'posts#show_by_day', :as => 'archived_blog'

  get '/archive', :to => 'comics#archive', :as => 'archive'
  get '/tagged/:tag', :to => 'comics#tagged', :as => 'tagged'

  post '/comments/:parent_type/:parent_id', :to => 'comments#create', :as => 'comment'

  #get "sign_in", :to => "devise/sessions#new"
  #get "sign_up", :to => "devise/users#new"

  resources :posts, :only => [:index, :show], :path => 'blog'
  resources :comics, :only => [:index, :show]

  resources :books, :only => [:index, :show] do
    resource :chapters, :only => [:index, :show] do
      resources :comics, :only => [:index, :show]
    end
    resources :comics, :only => [:index, :show]
  end

  namespace :manage do
    get 'settings', :to => 'settings#show', :as => 'settings'
    post 'settings', :to => 'settings#update'
    resources :books
    resources :chapters
    resources :comics
    resources :users
    resources :posts
    resources :tags
  end

  match "/404", :to => "errors#not_found"
  match "/500", :to => "errors#server_side"

  root :to => 'comics#show'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comic_id, :message, :user_id

  belongs_to :user
  belongs_to :commentable, :polymorphic => true

  scope :reversed, order("created_at DESC")

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authorize
  before_filter :get_parent_object

  def create
    @comment = current_user.comments.new(params[:comment])
    @comment.commentable_type = params[:parent_type]
    @comment.commentable_id = params[:parent_id]
    respond_to do |format|
      if @comment.save
        format.js
        format.html { redirect_to @comment.commentable, notice: 'Thank you for your comment.' }
      else
        format.js
        format.html { render action: "new" }
      end
    end
  end

  protected

  def get_parent_object
  #  @parent = case params[:parent_type]
  #    when 'Comic' then Comment.find params[:parent_id]
  #    when 'Post' then Post.find params[:parent_id]
  #    else nil
  #  end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
= div_for comment, :class => "well#{comment.user.admin ? ' alert alert-info' : ''}" do
  .pull-right
    %i= "Posted #{time_ago_in_words(comment.created_at)} ago by #{comment.user.name}"
  .span1= image_tag "http://www.gravatar.com/avatar/" + Digest::MD5.hexdigest(comment.user.email), :class => "pull-left"
  .span6= comment.message
  .clearfix

app/views/comments/_form.html.haml
= form_for @comment, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :user_id, :class => 'control-label'
    .controls
      = f.number_field :user_id, :class => 'number_field'
  .control-group
    = f.label :comic_id, :class => 'control-label'
    .controls
      = f.number_field :comic_id, :class => 'number_field'
  .control-group
    = f.label :message, :class => 'control-label'
    .controls
      = f.text_area :message, :class => 'text_area'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), comments_path, :class => 'btn'

app/views/comments/create.js.haml
$('#comments').prepend("#{escape_javascript(render :partial => @comment)}");
$('#new_comment')[0].reset();
$("#comment_#{@comment.id}").effect("highlight", {}, 3000);