config/routes.rb
ComicBook::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'profile',      :to => 'users#show',    :as => 'profile'
  get 'profile/edit', :to => 'users#edit',    :as => 'edit_profile'
  put 'profile',      :to => 'users#update',  :as => 'update_profile'

  get '/comic/:year/:month/:day', :to => 'comics#show_by_day', :as => 'archived'
  get '/blog/:year/:month/:day', :to => 'posts#show_by_day', :as => 'archived_blog'

  get '/archive', :to => 'comics#archive', :as => 'archive'
  get '/tagged/:tag', :to => 'comics#tagged', :as => 'tagged'

  post '/comments/:parent_type/:parent_id', :to => 'comments#create', :as => 'comment'

  #get "sign_in", :to => "devise/sessions#new"
  #get "sign_up", :to => "devise/users#new"

  resources :posts, :only => [:index, :show], :path => 'blog'
  resources :comics, :only => [:index, :show]

  resources :books, :only => [:index, :show] do
    resource :chapters, :only => [:index, :show] do
      resources :comics, :only => [:index, :show]
    end
    resources :comics, :only => [:index, :show]
  end

  namespace :manage do
    get 'settings', :to => 'settings#show', :as => 'settings'
    post 'settings', :to => 'settings#update'
    resources :books
    resources :chapters
    resources :comics
    resources :users
    resources :posts
    resources :tags
  end

  match "/404", :to => "errors#not_found"
  match "/500", :to => "errors#server_side"

  root :to => 'comics#show'

end

app/models/comic.rb
require 'watermark'

class Comic < ActiveRecord::Base

  attr_accessible :description, :name, :publish_date, :series_id, :image, :sold, :book_id

  belongs_to :chapter

  has_attached_file :image,
                    :styles => {
                        :original => {
                            :geometry => '800x600>',
                            :watermark_path => "#{Rails.root}/public/original_watermark.png"
                        },
                        :thumb => {
                            :geometry => '100x100>',
                            :watermark_path => "#{Rails.root}/public/thumb_watermark.png"
                        }
                    },
                    :url => '/comics/:id/:style/:filename',
                    :default_url => "/assets/none_:style.png",
                    :processors => [:watermark]


  validates_presence_of :name, :image
  validates_uniqueness_of :name, :publish_date

  has_many :comments, :as => :commentable

  belongs_to :book
  has_many :taggings
  has_many :tags, :through => :taggings

  after_create :increment_book

  scope :reversed, order("publish_date DESC")
  scope :latest, order("publish_date DESC").limit(1)
  scope :oldest, order("publish_date ASC").limit(1)
  scope :published, where("publish_date <= ?", Date.today)
  scope :for_month, lambda { |date|
    where("publish_date between ? and ?", date, date + 1.month)
  }
  scope :available, where("publish_date <= ? ", Date.today)
  scope :before, lambda { |date|
    where("publish_date < ? ", date).
      latest
  }
  scope :after, lambda { |date|
    where("publish_date > ? ", date).
      oldest
  }

  def previous
    Comic.before(self.publish_date).latest.first
  end
  def next
    Comic.after(self.publish_date).oldest.first
  end

  private

  def increment_book
    unless !Settings.uses_books && self.book_id.blank?
      self.book.increment_counter
    end
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController

  before_filter :get_linked

  def index
    @comics = Comic.available.latest.limit(10)
    @comic = @comics.first

    respond_to do |format|
      format.html do
        get_calendar
      end
      format.rss  { render :layout => false }
      format.atom { render :layout => false }
    end
  end

  def archive
    @comics = Comic.group(&:"YEAR(publish_date)").available.group(&:"MONTH(publish_date)").order("publish_date desc")
  end

  def tagged
    @tag = Tag.find_by_name params[:tag]
    redirect_to root_url unless @tag
    @comics = @tag.comics.available.group(&:"YEAR(publish_date)").group(&:"MONTH(publish_date)").order("publish_date asc")
  end

  def show
    if params[:id]
      @comic = Comic.find(params[:id])
    else
      @comic = Comic.available.latest.first
    end
    get_calendar
  end

  def show_by_day
    @date = Date.parse "#{params[:day]}-#{params[:month]}-#{params[:year]}"
    @comic = Comic.available.where(:publish_date => @date).first || nil
    get_calendar
  end

  protected

  def get_linked
    @first  = Comic.oldest.available.first
    @latest = Comic.latest.available.first
  end

  def get_calendar
    today = Date.today
    unless @date
      if @comic
        @date = @comic.publish_date
      else
        @date = today
      end
      @date = today if @comic.publish_date > today
    end
    @comics_for_month = {}
    Comic.for_month(Date.new(@date.year, @date.month)).available.each do |c|
      @comics_for_month[c.publish_date.day] = c
    end
    @first_day = Date.new(@date.year, @date.month).wday - 1
    @num_days = Time.days_in_month(@date.month)
  end

end

app/helpers/comics_helper.rb
module ComicsHelper

  def archived_comic_path comic
    return "#" unless comic
    archived_path(comic.publish_date.year, comic.publish_date.month, comic.publish_date.day)
  end

  def archived_comic_url comic
    return "#" unless comic
    archived_url(comic.publish_date.year, comic.publish_date.month, comic.publish_date.day)
  end

end

app/views/comics/_calendar.html.haml
%table.calendar.table-striped.table-condensed
  %thead
    %tr
      %th{ rowspan: 2}= link_to "".html_safe, archived_path(@date.year - 1, @date.month, 1), :class => "icon-backward", :title => "L:ast year"
      %th{ rowspan: 2}= link_to "".html_safe, archived_path((@date - 1.month).year, (@date - 1.month).month, 1), :class => "icon-step-backward", :title => "Last month"
      %th{ colspan: 3}= @date.year
      %th{ rowspan: 2}= link_to "".html_safe, archived_path((@date + 1.month).year, (@date + 1.month).month, 1), :class => "icon-step-forward", :title => "Next month"
      %th{ rowspan: 2}= link_to "".html_safe, archived_path(@date.year + 1, @date.month, 1 ), :class => "icon-forward", :title => "Next year"
    %tr
      %th{ colspan: 3}= content_tag :span, (Date::MONTHNAMES[@date.month])
    %tr
      %th S
      %th M
      %th T
      %th W
      %th T
      %th F
      %th S
  %tbody
    - (0..5).each do |r|
      %tr
        - (0..6).each do |c|
          - dt = c + r * 7 - @first_day
          %td{ class: (@comic and dt == @comic.publish_date.day) ? "current" : "" }
            - unless dt > @num_days or dt < 1
              - if @comics_for_month[dt].blank?
                = content_tag :span, dt
              - else
                = link_to dt, archived_path(@date.year, @date.month, dt)

app/views/comics/_comic.html.haml
.page-header
  %h1
    = "#{@comic.book.name} :: " if Settings.uses_books && @comic && @comic.book
    = @comic.name if @comic

.row
  .span2
    = render :partial => "shared/social"
    = render :partial => "shared/ads"

  .span8.comic
    = @comic ? image_tag(@comic.image.url(:original), :title => @comic.name, :class => "shadowed") : image_tag("none.png", :title => "No comic found", :class => "shadowed")
    %br
    %br
    %i= @comic.blank? ? "No comic found" : @comic.description
    %br
    %br
    %ul.pager
      %li{ :class => "previous #{@first==@comic ? 'disabled' : '' }" }
        = link_to "&laquo; First".html_safe, archived_comic_path(@first),            :title => "First", :class => "btn btn-large "
      %li{ :class => "#{(@comic && @comic.previous) ? '' : 'disabled' }" }
        - if @comic && @comic.previous
          = link_to "&larr; Previous".html_safe, archived_comic_path(@comic.previous), :title => "Previous", :class => "btn btn-large "
        - else
          = link_to "&larr; Previous".html_safe, "#",                                  :title => "Previous", :class => "btn btn-large disabled"
      %li{ :class => "#{(@comic && @comic.next) ? '' : 'disabled' }" }
        - if @comic && @comic.next
          = link_to "Next &rarr;".html_safe, archived_comic_path(@comic.next),         :title => "Next", :class => "btn btn-large"
        - else
          = link_to "Next &rarr;".html_safe, "#",                                      :title => "Next", :class => "btn btn-large disabled"
      %li{ :class => "next #{@latest==@comic ? 'disabled' : '' }" }
        = link_to "Latest &raquo;".html_safe, archived_comic_path(@latest),          :title => "Latest", :class => "btn btn-large "
    %br
    - if @comic
      .row
        .span2 &nbsp;
        .span8
          %h2 Comments
          - if signed_in?
            = form_for Comment.new, :url => comment_path(:parent_type => 'Comic', :parent_id => @comic.id), :remote => true do |f|
              = f.text_area :message, :class => "span8", :rows => 4
              %br
              = f.submit "Comment as #{current_user.name}", :class => "btn btn-primary pull-right"
          - else
            = link_to "Sign in", new_session_path("user")
            |
            = link_to "Sign in with Facebook", omniauth_authorize_path("user", "facebook")
          %br
          .clearfix
          #comments= render @comic.comments.reversed
  .span2
    = render :partial => "calendar", :locals => { :date => @date }
    = render :partial => "tags", :locals => { :tags => @comic.tags } if @comic

  .span4 &nbsp;

app/views/comics/_tags.html.haml
%br
%h3 Tags
- tags.each do |tag|
  = link_to tag.name, tagged_path(tag.name), :class => "btn"

app/views/comics/archive.html.haml
.page-header
  %h1 The Archives

- active = false
- comics_by_year = @comics.group_by { |c| c.publish_date.year }
#archiveCarousel.carousel.slide
  .carousel-inner
    - comics_by_year.each do |year, comics|
      - cls = "item"
      - unless active
        - cls += " active"
        - active = true
      %div{ :class => cls }
        %h2.alert-info=year
        %ul.unstyled.indented.span8
          - comics_by_month = comics.group_by { |y| y.publish_date.month }
          - comics_by_month.each do |month, comics|
            %li.span10
              %h3.alert-warning= t("date.month_names")[month]
              %ul.unstyled.span8.indented
                - comics.each do |c|
                  %li= link_to "#{c.publish_date.day.ordinalize} :: #{c.name}", archived_path(year, month, c.publish_date.day)
              %br
              %br
            %br
          %br
  %a.carousel-control.left{ :href  => "#archiveCarousel", :"data-slide" => "prev" }‹
  %a.carousel-control.right{ :href => "#archiveCarousel", :"data-slide" => "next" }›

app/views/comics/index.html.haml
= render :partial => "comic"

app/views/comics/show.html.haml
= render :partial => "comic"

app/views/comics/show_by_day.html.haml
= render :partial => "comic"

app/views/comics/tagged.html.haml
.page-header
  %h1= "Tagged as #{@tag.name}"

.row
  .span2 &nbsp;
  .span8.indented
    - comics_by_year = @comics.group_by { |c| c.publish_date.year }
    - comics_by_year.each do |year, comics|
      .row
        .well.label-info.label
          %h2=year
        %ul.unstyled.indented.span7
          - comics_by_month = comics.group_by { |y| y.publish_date.month }
          - comics_by_month.each do |month, comics|
            %li
              .row
                .well= link_to t("date.month_names")[month], archived_path(year, month, comics.first.publish_date.day)
                %ul.unstyled.span6.indented
                  - comics.each do |c|
                    %li= link_to "#{c.publish_date.day.ordinalize} :: #{c.name}", archived_path(year, month, c.publish_date.day)
            %br
      %br