config/routes.rb
ComicBook::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'profile',      :to => 'users#show',    :as => 'profile'
  get 'profile/edit', :to => 'users#edit',    :as => 'edit_profile'
  put 'profile',      :to => 'users#update',  :as => 'update_profile'

  get '/comic/:year/:month/:day', :to => 'comics#show_by_day', :as => 'archived'
  get '/blog/:year/:month/:day', :to => 'posts#show_by_day', :as => 'archived_blog'

  get '/archive', :to => 'comics#archive', :as => 'archive'
  get '/tagged/:tag', :to => 'comics#tagged', :as => 'tagged'

  post '/comments/:parent_type/:parent_id', :to => 'comments#create', :as => 'comment'

  #get "sign_in", :to => "devise/sessions#new"
  #get "sign_up", :to => "devise/users#new"

  resources :posts, :only => [:index, :show], :path => 'blog'
  resources :comics, :only => [:index, :show]

  resources :books, :only => [:index, :show] do
    resource :chapters, :only => [:index, :show] do
      resources :comics, :only => [:index, :show]
    end
    resources :comics, :only => [:index, :show]
  end

  namespace :manage do
    get 'settings', :to => 'settings#show', :as => 'settings'
    post 'settings', :to => 'settings#update'
    resources :books
    resources :chapters
    resources :comics
    resources :users
    resources :posts
    resources :tags
  end

  match "/404", :to => "errors#not_found"
  match "/500", :to => "errors#server_side"

  root :to => 'comics#show'

end

app/views/shared/_ads.html.haml
#ads_left= Settings.ads_code

app/views/shared/_errors.html.haml
- if obj && obj.errors.any?
  .row
    .span2 &nbsp;
    .span8.control-group
      %h2= "#{pluralize(obj.errors.count, "error")} prohibited this post from being saved:"
      %ul.well.btn-danger.unstyled
        - obj.errors.full_messages.each do |msg|
          %li= msg

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/shared/_navigation.html.haml
= link_to Settings.site_title, root_path, :class => 'brand'
%ul.nav
  - if Settings.uses_blog
    %li= link_to "Blog", posts_path
  %li= link_to "Archive", archive_path
  - if Settings.facebook_page
    %li= link_to "Facebook", Settings.facebook_page
%ul.nav.pull-right
  - if signed_in? and current_user.admin
    %li.dropdown
      %a.dropdown-toggle.text-warning{:href => "#", :"data-toggle" => "dropdown"}
        Management
        %b.caret
      %ul.dropdown-menu
        %li= link_to content_tag(:i, " ", :class => "icon-cog" ) + " Settings", manage_settings_path
    %li.dropdown
      %a.dropdown-toggle{:href => "#", :"data-toggle" => "dropdown"}
        Comics
        %b.caret
      %ul.dropdown-menu
        %li= link_to content_tag(:i, " ", :class => "icon-cog" ) + " Manage", manage_comics_path
        %li= link_to content_tag(:i, " ", :class => "icon-plus" ) + " New", new_manage_comic_path
    - if Settings.uses_books
      %li.dropdown
        %a.dropdown-toggle{:href => "#", :"data-toggle" => "dropdown"}
          Books
          %b.caret
        %ul.dropdown-menu
          %li= link_to content_tag(:i, " ", :class => "icon-cog" ) + " Manage", manage_books_path
          %li= link_to content_tag(:i, " ", :class => "icon-plus" ) + " New", new_manage_book_path
    %li.dropdown
      %a.dropdown-toggle{:href => "#", :"data-toggle" => "dropdown"}
        Tags
        %b.caret
      %ul.dropdown-menu
        %li= link_to content_tag(:i, " ", :class => "icon-cog" ) + " Manage", manage_tags_path
        %li= link_to content_tag(:i, " ", :class => "icon-plus" ) + " New tag", new_manage_tag_path
    - if Settings.uses_blog
      %li.dropdown
        %a.dropdown-toggle{:href => "#", :"data-toggle" => "dropdown"}
          My blog
          %b.caret
        %ul.dropdown-menu
          %li= link_to content_tag(:i, " ", :class => "icon-cog" ) + " Manage", manage_posts_path
          %li= link_to content_tag(:i, " ", :class => "icon-plus" ) + " New post", new_manage_post_path
  - if signed_in?
    %li.dropdown
      %a.dropdown-toggle{:href => "#", :"data-toggle" => "dropdown"}
        = current_user.name
        %b.caret
      %ul.dropdown-menu
        %li= link_to content_tag(:i, " ", :class => "icon-user" ) + " View account", profile_path
        %li= link_to content_tag(:i, " ", :class => "icon-edit" ) + " Edit account", edit_profile_path
        %li= link_to content_tag(:i, " ", :class => "icon-off" ) + " Logout", destroy_user_session_path, :method => :delete
  - else
    %li= link_to('Sign up', new_user_registration_path)
    %li= link_to('Sign in', new_user_session_path)
    %li= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)

app/views/shared/_social.html.haml
- if @comic or @post
  - if @comic
    - url = archived_url(@comic.publish_date.year, @comic.publish_date.month, @comic.publish_date.day)
    - rss_url = comics_url(:format => :atom)
  - else
    - url = archived_blog_url(@post.created_at.year, @post.created_at.month, @post.created_at.day)
    - rss_url = posts_url(:format => :atom)
  - esc_url = URI.escape(url)

  %ul.unstyled.well.alert-info
    %li
      = link_to image_tag('fb_share.png'), "https://www.facebook.com/dialog/feed?app_id=#{Settings.facebook_app_id}&link=#{esc_url}", :title => "Share this on Facebook"
      %br
      %br
    %li
      = link_to image_tag('twitter.png'), "http://twitter.com/share?url=#{url}", :title => "Tweet this!"
      = link_to(image_tag('feed-icon-28x28.png'), rss_url, :title => "Grab the RSS feed")
      %br
      %br
    %li
      .g-plusone
    %li
      .fb-like{ :"data-href" => esc_url, :"data-send" => "false", :"data-layout" => "box_count", :"data-width" => "450", :"data-show-faces" => "false", :"data-font" => "arial"}
      %br
      %br
    %li= link_to "Permalink", url